AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  DynamoVinylsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: vinyls
      PrimaryKey:
        Name: id
        Type: String
  CreateVinylFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://vinyls-api/9f1ed417d133760d1b1a8cb9d78c8078
      Handler: create-vinyl.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs12.x
      Events:
        CreateVinyl:
          Type: Api
          Properties:
            Path: /vinyls
            Method: post
