AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  DynamoVinylsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: vinyls
      PrimaryKey:
        Name: id
        Type: String
