AWSTemplateFormatVersion: "2010-09-09" # (1)
Transform: AWS::Serverless-2016-10-31 # (1)
Resources: # (2)
  DynamoVinylsTable: # (3)
    Type: AWS::Serverless::SimpleTable # (4)
    Properties:
      TableName: vinylss # (5)
      PrimaryKey:
        Name: id # (6)
        Type: String