AWSTemplateFormatVersion: "2010-09-09" # (1)
Transform: AWS::Serverless-2016-10-31 # (1)
Resources: # (2)
  DynamoVinylsTable: # (3)
    Type: AWS::Serverless::SimpleTable # (4)
    Properties:
      TableName: vinyls # (5)
      PrimaryKey:
        Name: id # (6)
        Type: String
  CreateVinylFunction: # 1
    Type: AWS::Serverless::Function # 2
    Properties:
      CodeUri: src/ # 3
      Handler: create-vinyl.handler # 4
      Policies: AmazonDynamoDBFullAccess # 5
      Runtime: nodejs12.x
      Events:
        CreateVinyl: # 6
          Type: Api
          Properties:
            Path: /vinyl #7
            Method: post
  GetVinylsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get-vinyls.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs12.x
      Events:
        GetVinyls:
          Type: Api
          Properties:
            Path: /vinyls
            Method: get